
# Board settings.
#BOARD = atmega328
BOARD = pro5v328

# Where to find header files and libraries.
#INC_DIRS = ./inc
#LIB_DIRS = $(addprefix $(ARD_HOME)/libraries/, $(LIBS))
#LIBS =

INC_DIRS = ../
LIB_DIRS = /usr/share/arduino-100/libraries/Wire /usr/share/arduino-100/libraries/Wire/utility ../../../libs/SdFat ../../../libs/jeelib/ /usr/share/arduino-100/libraries/SPI/

include ../Makefile.master

